# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-job-sa
  namespace: deploy-test

---

# Role to allow access to services
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: deploy-test
  name: test-job
rules:
  - apiGroups: [""]
    resources: ["services","pods"]
    verbs: ["get", "list", "watch"]

---

# RoleBinding to bind the Service Account to the Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-jobbinding
  namespace: deploy-test
subjects:
  - kind: ServiceAccount
    name: test-job-sa
    namespace: deploy-test
roleRef:
  kind: Role
  name: test-job
  apiGroup: rbac.authorization.k8s.io
---
# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-job-sa
  namespace: production

---

# Role to allow access to services
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: production
  name: test-job
rules:
  - apiGroups: [""]
    resources: ["services","pods"]
    verbs: ["get", "list", "watch"]

---

# RoleBinding to bind the Service Account to the Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-jobbinding
  namespace: production
subjects:
  - kind: ServiceAccount
    name: test-job-sa
    namespace: production
roleRef:
  kind: Role
  name: test-job
  apiGroup: rbac.authorization.k8s.io