apiVersion: v1
kind: Service
metadata:
  name: my-production-svc-test
  namespace: deploy-test
spec:
  ports:
    - nodePort: 31112
      port: 3000
      targetPort: 3000
  selector:
    app: example
  type: NodePort