apiVersion: apps/v1
kind: Deployment
metadata:
  name: production
  namespace: default


spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: example


    spec:
      containers:
      - name: poding
        image: yagnesh.jariwala.com:30002/inventyv/production:${trigger.parameters.version}
        imagePullPolicy: Always
