apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-server
  namespace: test
spec:
  selector:
    matchLabels:
      app: mongo-server
  serviceName: my-service
  replicas: 2
  template:
    metadata:
      labels:
        app: mongo-server
    spec:
      containers:
        - name: mongo-server
          image: mongo
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: test
spec:
  selector:
    app: mongo-server
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30004
  type: NodePort