{
 "title": "Task management",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU utilization per POD",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"production\"}[$__range])) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory utilization per POD",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{namespace=\"production\",container=\"poding\"}[$__range])) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "App Liveness",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "up{job=\"flask-app\"}",
     "legendFormat": " Status"
    }
   ]
  },
  {
   "title": "Request rate by STATUS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(task_management_app_http_request_total[$__range])",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": " Error Rates (4xx, 5xx)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(task_management_app_http_request_total{status=~\"[45].*\"}[$__range])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request rate by PATH",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(task_management_app_http_request_duration_seconds_sum{path!~\"^/static/assets.*\", path!=\"\"}[$__range])) by(status, path)",
     "legendFormat": "{{status}} {{path}}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"database\"}[$__range])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# sum(container_memory_working_set_bytes{namespace=\"database\"})\r\nsum(rate(container_memory_usage_bytes{namespace=\"database\"}[$__range])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk IO utilization",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"database\"}[$__range])) by (device)\r\n+\r\nsum(rate(container_fs_reads_bytes_total{namespace=\"database\"}[$__range])) by (device)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"database\"}[$__range])) by (pod)\r\n+\r\nsum(rate(container_network_receive_bytes_total{namespace=\"database\"}[$__range])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Unavailable pod(s)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_unavailable{namespace=\"production\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready pod(s)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 26 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"production\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Required pod(s)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=\"production\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Restart status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{namespace=\"database\"}[$__range])) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{namespace=\"production\"}[$__range])) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU IDLE %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (sum(rate(node_cpu_seconds_total{mode=\"idle\"}[$__range])) / sum(rate(node_cpu_seconds_total[$__range])) * 100)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(task_management_app_http_request_duration_seconds_sum{status=~\"[23].*\"}[$__range]) / rate(task_management_app_http_request_duration_seconds_count{status=~\"[23].*\"}[$__range])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(task_management_app_http_request_total) "
    }
   ]
  },
  {
   "title": "Total Requests per STATUS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(task_management_app_http_request_total{method=\"GET\"}) by(status)",
     "legendFormat": "HTTP Status: {{status}}"
    }
   ]
  }
 ]
}