{
 "title": "Yagnesh",
 "time": { "from": "2025-04-08T08:57:57.328Z", "to": "2025-04-08T09:07:57.328Z" },
 "refresh": "5s",
 "panels": [
  { "title": "Database side", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory and CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"database\"}[1m])) by (pod) * 100",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"database\"}) by (pod) / 1000000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"database\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "K8s side", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Ready",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"production\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_unavailable{namespace=\"production\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kube_deployment_status_replicas_available{namespace=\"production\"} / kube_deployment_status_replicas{namespace=\"production\"}\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Restart status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{namespace=\"database\"}[5m])) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{namespace=\"production\"}[5m])) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 13 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=\"production\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(task_management_app_http_request_total) "
    }
   ]
  },
  {
   "title": "Requests Per Status Code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(task_management_app_http_request_total{method=\"GET\"}) by(status)",
     "legendFormat": "HTTP Status: {{status}}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "    rate(task_management_app_http_request_duration_seconds_sum{status!~\"3.*\"}[1m]) / rate(task_management_app_http_request_duration_seconds_count{status!~\"3.*\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "Application Side", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Response Time (P99, P95, P50)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(task_management_app_http_request_duration_seconds_bucket[5m])) by (le)) ",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(task_management_app_http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(task_management_app_http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "HTTP Request Rate (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "rate(task_management_app_http_request_total[1m])",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "App Health Check Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "up{job=\"flask-app\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"production\"}[1m])) by (pod) * 100",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(container_memory_usage_bytes{namespace=\"production\",container=\"poding\"}[1m])) by(pod) / 1000000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": " Error Rates (4xx, 5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(rate(task_management_app_http_request_total{status=~\"4.*\"}[1m]))",
     "legendFormat": "Error 404"
    },
    {
     "expr": "sum(rate(task_management_app_http_request_total{status=~\"5.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(task_management_app_http_request_duration_seconds_sum[1m])) by(status,path)",
     "legendFormat": "{{status}} {{path}}"
    }
   ]
  }
 ]
}