{
 "title": "Flask Monitoring",
 "description": "Flask Monitoring with StatsD",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(flask_info{}, app_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(task_management_app_http_request_total{method=\"GET\",status=\"200\"}) "
    },
    {
     "expr": "sum (flask_request_status_total{app_name=\"$app_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Status Code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(task_management_app_http_request_total{method=\"GET\"}) by(status)",
     "legendFormat": "HTTP Status: {{status}}"
    },
    {
     "expr": "sum (flask_request_status_total{app_name=\"$app_name\"}) by(status)",
     "legendFormat": "HTTP Status: {{status}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "task_management_app_http_request_duration_seconds_sum / task_management_app_http_request_duration_seconds_count",
     "legendFormat": "{{path}} {{method}}"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "task_management_app_http_request_duration_seconds_sum",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(task_management_app_http_request_duration_seconds_sum[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(task_management_app_http_request_total{ status=~\"2.*\"}) / sum(task_management_app_http_request_total) ",
     "legendFormat": "{{method}} {{endpoint}} "
    }
   ]
  },
  {
   "title": "Request Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "task_management_app_http_request_duration_seconds_sum / task_management_app_http_request_duration_seconds_count",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}