name: Docker Image CI

on:
  push:
    branches: [ "main" ]


jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4


    - name: Build the Docker image
      run: docker build -t yagnesh.jariwala.com:30002/inventyv/production .
    - name: Push the Docker image
      run: docker push yagnesh.jariwala.com:30002/inventyv/production

